MENSAJE_USARIO_YA_EXISTE = 'Este correo electrónico ya se encuentra ocupado por otro usuario, si desea continuar con el registro, cambie el correo'
MENSAJE_FECHA_POSTERIOR = 'Fecha invalida NO debe ser una fecha posterior a la de hoy'
MENSAJE_FECHA_ANTERIOR = 'Fecha invalida debe ser una fecha posterior a la de hoy'
MENSAJE_FECHA_INVALIDA = 'Verifique que la fecha tenga el formato DD/MM/AAAA y que sea un dia valido. Ejemplo: 01/01/2023'
MENSAJE_USUARIO_INVALIDO = 'Usuario incorrecto, revise que el email sea correcto y que el cliente este registrado'
MENSAJE_SOLO_LETRAS = 'Solo se permiten letras, no ingrese numeros, ni simbolos como #,$,/, etc.'
MENSAJE_SOLO_NUMEROS = "Solo se permiten números, no ingrese simbolos como .,-, /, etc."
MENSAJE_ARCHIVO_TURNOS = "Archivo invalido, verifique que el archivo sea de tipo .csv, .xls o .xlsx y que dentro tenga columnas con: fechas con el formato DD/MM/AAAA, nombre de la veterinaria y dirección en ese orden"
MENSAJE_NO_HAY_VETERINARIAS = "No se encuentra el listado de veterinarias de turno"
MENSAJE_IMAGEN_INVALIDA = "Imagen invalida, verifique que el archivo sea de tipo .jpg, .png o jpeg"
MENSAJE_MASCOTA_YA_PERDIDA = "Esta mascota ya esta registrada en mascotas perdidas"
MENSAJE_SIN_VISITAS= "Sin vacunaciones o desparasitaciones registradas"
MENSAJE_SIN_TURNOS = "Sin turnos solicitados"