# Generated by Django 4.2 on 2023-06-11 01:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Campania', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donaciones',
            name='cliente',
        ),
        migrations.AddField(
            model_name='donaciones',
            name='usuario',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
