# Generated by Django 4.2 on 2023-06-12 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Campania', '0004_alter_donaciones_campania'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonacionesVisitantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campania', models.CharField(max_length=255)),
                ('correo', models.EmailField(max_length=254)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
