# Generated by Django 4.1.5 on 2023-06-04 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MascotasEncontradas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contacto', models.CharField(max_length=100, null=True)),
                ('descripcion', models.CharField(max_length=300)),
                ('foto', models.ImageField(blank=True, upload_to='mascotas_encontradas/')),
                ('devuelto', models.BooleanField(blank=True, default=False)),
            ],
        ),
    ]
