# Generated by Django 4.1.5 on 2023-06-04 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_visitas_cant_desparacitante_visitas_codigo_and_more'),
        ('mascotas_encontradas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascotasencontradas',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.cliente'),
        ),
    ]
