# Generated by Django 4.1.5 on 2023-06-07 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas_encontradas', '0002_mascotasencontradas_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascotasencontradas',
            name='direccion',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
