# Generated by Django 4.1.5 on 2023-05-02 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campana',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('motivo', models.CharField(max_length=50)),
                ('fecha_fin', models.DateTimeField()),
                ('Total_donado', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('raza', models.CharField(max_length=1000)),
                ('fecha_nac', models.DateField()),
                ('foto', models.FileField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Mascota_Adopcion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('raza', models.CharField(max_length=1000)),
                ('fecha_nac', models.DateField()),
                ('estado', models.CharField(blank=True, choices=[('a', 'Adoptado'), ('e', 'Esperando')], default='e', help_text='Estado del perro', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('dni', models.IntegerField()),
                ('direccion', models.CharField(max_length=200)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Red_Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('usuario', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.persona')),
                ('mascotas', models.ManyToManyField(blank=True, to='main.mascota')),
                ('mascotas_adopcion', models.ManyToManyField(blank=True, to='main.mascota_adopcion')),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('asistio', models.BooleanField()),
                ('motivo', models.CharField(max_length=50)),
                ('aceptado', models.BooleanField()),
                ('turnos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Prestador_Servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('p', 'Paseador'), ('c', 'Cuidador')], default='p', help_text='Tipo de servicio que presta la persona', max_length=1)),
                ('datos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.persona')),
                ('redes', models.ManyToManyField(to='main.red_social')),
            ],
        ),
        migrations.CreateModel(
            name='PersonaRedSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.persona')),
                ('red_social', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.red_social')),
            ],
        ),
        migrations.AddField(
            model_name='mascota_adopcion',
            name='dueno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.usuario'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='dueno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.usuario'),
        ),
    ]
