# Generated by Django 4.1.5 on 2023-05-04 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='nombre_usuario',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
