# Generated by Django 4.1.5 on 2023-05-02 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='datos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.persona'),
        ),
    ]
