# Generated by Django 4.1.5 on 2023-05-12 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_user_is_veterinario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_veterinario',
            field=models.BooleanField(null=True),
        ),
    ]
