# Generated by Django 4.1.5 on 2023-05-02 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_usuario_datos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='datos',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='mascotas',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='mascotas_adopcion',
        ),
        migrations.RemoveField(
            model_name='prestador_servicios',
            name='redes',
        ),
        migrations.AddField(
            model_name='cliente',
            name='datos',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='main.persona'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='mascotas',
            field=models.ManyToManyField(blank=True, to='main.mascota'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='mascotas_adopcion',
            field=models.ManyToManyField(blank=True, to='main.mascota_adopcion'),
        ),
        migrations.AddField(
            model_name='red_social',
            name='dueno',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='main.prestador_servicios'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mascota',
            name='dueno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.cliente'),
        ),
        migrations.AlterField(
            model_name='mascota_adopcion',
            name='dueno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.cliente'),
        ),
        migrations.DeleteModel(
            name='PersonaRedSocial',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
