# Generated by Django 4.1.5 on 2023-05-03 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_usuario_datos_remove_usuario_mascotas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='foto',
            field=models.FileField(blank=True, upload_to='imaganes/'),
        ),
    ]
