# Generated by Django 4.1.5 on 2023-05-05 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_cliente_is_active_remove_cliente_is_admin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turno',
            old_name='turnos',
            new_name='cliente',
        ),
        migrations.AddField(
            model_name='turno',
            name='banda_horaria',
            field=models.CharField(choices=[('M', 'Mañana'), ('T', 'Tarde')], default='M', help_text='Horario en el que puede ir a la veterinaria mañana(7 AM - 12 PM) o tarde (12 PM a 6 PM', max_length=1),
        ),
    ]
