# Generated by Django 4.1.5 on 2023-05-13 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_user_is_veterinario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='veterinario',
        ),
    ]
