# Generated by Django 4.1.5 on 2023-05-08 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_turno_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=50)),
                ('cantidad', models.IntegerField(default=0)),
                ('estado', models.CharField(choices=[('b', 'bloqueado'), ('n', 'no bloqueado')], default='n', max_length=1)),
            ],
        ),
    ]
