# Generated by Django 4.1.5 on 2023-05-13 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_turno_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='foto',
            field=models.FileField(blank=True, upload_to='imagenes/'),
        ),
    ]
