# Generated by Django 4.2 on 2023-05-08 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_intentos'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='veterinario',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
