# Generated by Django 4.1.5 on 2023-05-11 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_cliente_veterinario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='motivo',
            field=models.CharField(choices=[('C', 'Consulta'), ('U', 'Urgencia'), ('S', 'Castración'), ('A', 'Vacunación de tipo A'), ('B', 'Vacunación de tipo B'), ('D', 'Desparasitación')], default='C', max_length=1),
        ),
    ]
