# Generated by Django 4.1.5 on 2023-05-12 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_turno_motivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='estado',
            field=models.CharField(blank=True, choices=[('E', 'Esperando Confirmacion'), ('A', 'Aceptado'), ('R', 'Rechazado')], default='E', max_length=1),
        ),
    ]
