# Generated by Django 4.1.5 on 2023-05-12 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_turno_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turno',
            name='aceptado',
        ),
    ]
