# Generated by Django 4.1.5 on 2023-05-16 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_persona_correo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='red_social',
            old_name='nombre',
            new_name='nombre_red',
        ),
        migrations.RenameField(
            model_name='red_social',
            old_name='usuario',
            new_name='usuario_red',
        ),
    ]
