# Generated by Django 4.2 on 2023-05-17 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_vacuna_tipoa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacuna_tipoB',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_aplicacion', models.DateField()),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.mascota')),
            ],
        ),
    ]
