# Generated by Django 4.1.5 on 2023-05-21 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_prestador_servicios_zona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='banda_horaria',
            field=models.CharField(choices=[('Mañana', 'Mañana'), ('Tarde', 'Tarde')], default='Mañana', help_text='Mañana(7 a 12hs) - Tarde(12 a 18hs)', max_length=100),
        ),
        migrations.AlterField(
            model_name='turno',
            name='estado',
            field=models.CharField(blank=True, choices=[('Esperando Confirmacion', 'Esperando Confirmacion'), ('Aceptado', 'Aceptado'), ('Rechazado', 'Rechazado')], default='Esperando Confirmación', max_length=100),
        ),
        migrations.AlterField(
            model_name='turno',
            name='motivo',
            field=models.CharField(choices=[('Consulta', 'Consulta'), ('Urgencia', 'Urgencia'), ('Castración', 'Castración'), ('Vacunación de tipo A', 'Vacunación de tipo A'), ('Vacunación de tipo B', 'Vacunación de tipo B'), ('Desparasitación', 'Desparasitación')], default='Consulta', max_length=100),
        ),
    ]
