# Generated by Django 4.1.5 on 2023-06-02 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_visitas_fecha_visitas_mascota_visitas_motivo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitas',
            old_name='user_id',
            new_name='cliente',
        ),
        migrations.AlterField(
            model_name='visitas',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
    ]
