# Generated by Django 4.1.5 on 2023-06-06 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_campana_fecha_fin'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='perdida',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
