# Generated by Django 4.2 on 2023-06-05 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_campana_fecha_fin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='descuento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
