# Generated by Django 4.2 on 2023-06-05 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_user_descuento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='descuento',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
