# Generated by Django 4.1.5 on 2023-06-07 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_mascota_perdida'),
        ('main', '0025_alter_user_descuento'),
    ]

    operations = [
    ]
