# Generated by Django 4.1.5 on 2023-06-11 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_merge_0023_mascota_perdida_0025_alter_user_descuento'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitas',
            name='monto',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True),
        ),
    ]
