# Generated by Django 4.2 on 2023-06-12 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_visitas_monto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitas',
            name='monto',
            field=models.DecimalField(decimal_places=300, max_digits=6000, null=True),
        ),
    ]
