# Generated by Django 4.2 on 2023-06-12 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_visitas_monto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitas',
            name='monto',
            field=models.DecimalField(decimal_places=30, max_digits=60, null=True),
        ),
    ]
