# Generated by Django 4.1.5 on 2023-06-12 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_alter_visitas_monto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='estado',
            field=models.CharField(blank=True, choices=[('E', 'Esperando Confirmacion'), ('A', 'Aceptado'), ('R', 'Rechazado'), ('As', 'Asistio')], default='Esperando Confirmación', max_length=100),
        ),
    ]
