# Generated by Django 4.1.5 on 2023-06-12 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_turno_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='estado',
            field=models.CharField(blank=True, choices=[('E', 'Esperando Confirmacion'), ('A', 'Aceptado'), ('R', 'Rechazado'), ('As', 'Asistio'), ('Ca', 'Cancelado'), ('Fa', 'Falto')], default='Esperando Confirmación', max_length=100),
        ),
    ]
