# Generated by Django 4.1.5 on 2023-06-17 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_alter_turno_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='viva',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
