# Generated by Django 4.1.5 on 2023-06-30 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_mascota_viva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitas',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
