# Generated by Django 4.1.5 on 2023-07-04 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_alter_visitas_monto'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestador_servicios',
            name='vivo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='campana',
            name='fecha_fin',
            field=models.DateField(default='2023-07-04', error_messages={'invalid': 'Fecha incorrecta. Use el formato AAAA-MM-DD'}),
        ),
    ]
