# Generated by Django 4.1.5 on 2023-07-06 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_prestador_servicios_deshabilitado_hasta'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota_adopcion',
            name='vivo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='campana',
            name='fecha_fin',
            field=models.DateField(default='2023-07-06', error_messages={'invalid': 'Fecha incorrecta. Use el formato AAAA-MM-DD'}),
        ),
        migrations.AlterField(
            model_name='prestador_servicios',
            name='deshabilitado_hasta',
            field=models.DateField(default='2023-07-06', error_messages={'invalid': 'Fecha incorrecta. Use el formato AAAA-MM-DD'}),
        ),
    ]
