# Generated by Django 5.0.2 on 2024-05-17 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_mascota_adopcion_vivo_alter_campana_fecha_fin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campana',
            name='fecha_fin',
            field=models.DateField(default='2024-05-17', error_messages={'invalid': 'Fecha incorrecta. Use el formato AAAA-MM-DD'}),
        ),
        migrations.AlterField(
            model_name='prestador_servicios',
            name='deshabilitado_hasta',
            field=models.DateField(default='2024-05-17', error_messages={'invalid': 'Fecha incorrecta. Use el formato AAAA-MM-DD'}),
        ),
    ]
