# Generated by Django 4.1.5 on 2023-05-31 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Turno', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veterinarias_de_turno',
            name='archivo',
        ),
        migrations.AddField(
            model_name='veterinarias_de_turno',
            name='arch',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
