# Generated by Django 4.1.5 on 2023-06-01 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Turno', '0002_remove_veterinarias_de_turno_archivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veterinarias_de_turno',
            name='arch',
            field=models.FileField(blank=True, upload_to='archivos/'),
        ),
    ]
