# Generated by Django 4.1.5 on 2023-06-30 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Turno', '0004_cobro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobro',
            name='cliente',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='cobro',
            name='mascota',
            field=models.CharField(max_length=200),
        ),
    ]
