# Generated by Django 4.1.5 on 2023-06-03 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0021_visitas_cant_desparacitante_visitas_codigo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MascotasPerdidas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(null=True)),
                ('ultimo_lugar', models.CharField(max_length=100)),
                ('rasgos_particulares', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=300)),
                ('foto', models.FileField(blank=True, upload_to='mascotas_perdidas/media/fotos/')),
                ('encontrado', models.BooleanField(blank=True, default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.cliente')),
            ],
        ),
    ]
