# Generated by Django 4.1.5 on 2023-06-03 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas_perdidas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascotasperdidas',
            name='contacto',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
