# Generated by Django 4.1.5 on 2023-06-03 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_visitas_cant_desparacitante_visitas_codigo_and_more'),
        ('mascotas_perdidas', '0002_mascotasperdidas_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascotasperdidas',
            name='mascota',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.mascota'),
        ),
    ]
