# Generated by Django 4.1.5 on 2023-06-03 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas_perdidas', '0003_mascotasperdidas_mascota'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascotasperdidas',
            name='mascota',
        ),
    ]
