# Generated by Django 4.1.5 on 2023-06-03 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas_perdidas', '0004_remove_mascotasperdidas_mascota'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascotasperdidas',
            name='nombre',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mascotasperdidas',
            name='raza',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
