# Generated by Django 4.1.5 on 2023-06-06 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas_perdidas', '0007_alter_mascotasperdidas_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascotasperdidas',
            name='rasgos_particulares',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
