# Generated by Django 4.1.5 on 2023-06-24 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0033_mascota_viva'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioTinder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_de_celo', models.CharField(blank=True, max_length=100)),
                ('contacto', models.CharField(max_length=100)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.mascota')),
            ],
        ),
    ]
