# Generated by Django 4.1.5 on 2023-06-24 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tinder', '0002_usuariotinder_sexo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuariotinder',
            old_name='sexo',
            new_name='hembra',
        ),
    ]
