# Generated by Django 4.2 on 2023-06-28 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_mascota_viva'),
        ('tinder', '0003_rename_sexo_usuariotinder_hembra'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariotinder',
            name='dueno',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='main.cliente'),
            preserve_default=False,
        ),
    ]
