# Generated by Django 4.1.5 on 2023-07-01 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinder', '0004_usuariotinder_dueno'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariotinder',
            name='activa',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
