# Generated by Django 4.1.5 on 2023-07-05 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinder', '0005_usuariotinder_activa'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariotinder',
            name='foto',
            field=models.ImageField(default=1, upload_to='mascotas_match_perruno/'),
            preserve_default=False,
        ),
    ]
